# Experimental!
IncWeight ↚ (
  ↥⊸(↘¯⟜⌝↘1)
  ↥⊸(⌝↘¯⟜↘1)
  ≡(↥⊸(↘¯⟜⌝↘1))
  ≡(↥⊸(⌝↘¯⟜↘1))
)
Blur ↚ ⬚0⧈(÷⊃⧻/+♭)[11_11 1_1 5_5]
# text ? text height maincolor glowcolor backgroundcolor
GlowText ← (
  ⊃(⋅⋅⋅∘
  | layout:
    ⍥₃IncWeight
    ⍥₂Blur
  | ∵₁↙₃⬚∘layout⊃⋅⋅⋅⋅∘(:⊙□₂)
  | ⋅⋅∘
  )

  ⊸+⊙⟜≡⌟≡⌟≍ ≡⌞≡⌞×
  ≡≡⨬⊙◌◌ ⊃⋅⋅∘⊙∘
)

[Red Green Blue Purple Magenta Blue]
"Merry XMAS!"
≡⌟⊙⊃(50 White|⊢°⍆|Black)
≡GlowText
⤸1/⊂⤸0_2
